% view_ripactivtimes
% starts with struct mf generated by rungetripactivprob.m

days = m; % from variables declared in script rungetripactivprob.m
pf = 2; % shock track pf=1; ctrl pf=2; both = 3;  PLACE FIELD FILTER SUBSET
trk = 3; % shock = 2; ctrl = 3;        EPOCH FILTER
ripstart = 1;
t = ripstart;  % column for ripple start time


%cellnum.ctrl = size(mf{days}{pf}.output{trk.ctrl},2);
%cellnum.shock = size(mf{days}{pf}.output{epoch}(cell).times,2);
%cellnum.shock = size(mf{days}{pf}.output{2}(2).times,2);
%cellnum.ctrl = size(mf{days}{pf}.output{3}(2).times,2);

%
react = cell(1);
figure;
set(gcf, 'Position', [ 0,0,1600,400]); % double size of figure window
hold on;
for d = 1:days
    cellnum.shock = size(mf{d}{pf}.output{trk},2);
    animalname = mf{d}{pf}.animal{1};
    animal = animaldef(animalname, 'outputstruct', 1);
    estpos = loaddatastruct(animal.dir, animal.pre, 'estpos', d);
    
    behEpoch = mf{d}{pf}.epochs{trk}(2); % epoch of shock track behavior
    %behEpoch.ctrl = mf{d}{pf}.epochs{trk.ctrl}(2);
    
    % calculate ripple coactivations for shock track epoch
    riplist = [];
    for c = 1: cellnum.shock
        if ~isempty(mf{d}{pf}.output{trk}(c).times)
            riptimes = mf{d}{pf}.output{trk}(c).times(:,t);
            riplist = [riplist; riptimes];
        end
    [item, count] = sumreps(riplist);
    react{d} = [item count];    % list unique reactive ripples and coactive
    end


    % calculate ripple coactivations for ctrl track epoch
    %{
    riplist = [];
    for cell = 1: cellnum.ctrl
        riptimes = mf{day}{pf}.output{trk.ctrl}(cell).times(:,t);
        riplist = [riplist; riptimes];
        %out = somefunction(riplist);
        [item, count] = sumreps(riplist);
        react = [item count];    % list unique reactive ripples and coactive
    end
    %}

    %% plot all react ripples
    ep = behEpoch;    % epoch for estpos
    y = 1: size(react{d}(:,1));
    subplot(1,days,d);
    plot(react{d}(:,1), y);
    hold on;
    plot(react{d}(:,1), react{d}(:,2));
    plot(estpos{d}{ep}.data(:,1), estpos{d}{ep}.data(:,10), 'r');
    axis square;
end  
%% plot react min coactive cells
%{
ind = react(:,2) >3;
figure;
plot(react(ind,1))
hold on
plot(react(ind,2), react(ind,1)) 
%}



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%  somefunction()              %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function out = somefunction(riplist)
% somefunction will remove repeats and create a new colum listing the
% counts (count is one for unique values)
tmplist = sort(riplist);
[coact,time]=hist(tmplist, unique(tmplist));
out = [time coact'];


    